### ISSUE TITLE
TypeError: '`type` object is not subscriptable

### ISSUE THREAD

**Issue by ajensen1234** [mivanit/dendron-citations#1]
```
Traceback (most recent call last):
  File "refs_vault_gen.py", line 229, in <module>
    class CitationEntry:
  File "refs_vault_gen.py", line 244, in CitationEntry
    bib_meta : Optional[OrderedDict[str, str]] = None
TypeError: 'type' object is not subscriptable
```

I get this error when trying to run this. Any thoughts?

**Comment by mivanit** [comment]
Hi, I've pushed a commit that implements a "verbose" printing option. Could you pull and run the code again with `--verbose=True`, so we can narrow down which bibliography item is the problem?

**Comment by ajensen1234** [comment]
I don't seem to be getting any different output when I use the verbose output. I've cloned the repo and tried again. Also, I was using the example `bib.bib` and was still getting this error.

```
(refs) PS C:\Users\ajensen123\Documents\dendron-citations> python .\refs_vault_gen.py .\examples\bib.bib .\examples\vault --verbose==True
Traceback (most recent call last):
  File ".\refs_vault_gen.py", line 229, in <module>
    class CitationEntry:
  File ".\refs_vault_gen.py", line 244, in CitationEntry
    bib_meta : Optional[OrderedDict[str, str]] = None
TypeError: 'type' object is not subscriptable

```

**Comment by mivanit** [comment]
That's very strange... what version of python are you using?

I my only guess so far is that `OrderedDict[str, str]` isn't working because somehow it's not implemented as a type hint.

If the problem is the python version, you might be able to get it to work by changing line 244 from   
`bib_meta : Optional[OrderedDict[str, str]] = None`
to
`bib_meta : Optional[OrderedDict] = None`
(or just removing the type hint altogether)

**Comment by ajensen1234** [comment]
I upgraded to python `3.10.2` and it worked perfectly.

Thanks for the suggestion!

**Comment by mivanit** [comment]
awesome! could you let me know what python version it didn't work in, so I can add that to the readme and/or put some version checking in the code?

**Comment by ajensen1234** [comment]
`3.8.5`!
